version: '3.7'

services:
  app:
    build:
      context: .
      args:
        UID: "${UID}"
    user: "node"
    volumes:
      - '.:/usr/src/app'
      - 'node_modules:/usr/src/app/node_modules'

volumes:
  node_modules:
