version: '3.7'

services:
  app:
    image: node:10.15-alpine
    command: sh -c 'yarn && yarn start'
    working_dir: '/usr/src/app'
    volumes:
      - '.:/usr/src/app'
      - 'node_modules:/usr/src/app/node_modules'

volumes:
  node_modules:
